#!/usr/bin/bash

#SHIELD="splitkb_aurora_lily58"
SHIELD="splitkb_aurora_sofle"
ARGS="-p"

if [ ! -z $1 ]
then
    SHIELD=$1
fi

DIR=boards/${SHIELD}

_jq() {
    echo $1 | base64 -d - | jq -r $2
}

for b in $(yaml2json ${DIR}/build.yaml | jq '.include[] | @base64' -r)
do
    BOARD=$(_jq $b '.board')
    SHIELDS=$(_jq $b '.shield')
    SHIELD=$(echo ${SHIELDS} | cut -d' ' -f1)
    west build ${ARGS} -s ../app -d .build/${SHIELD} -b ${BOARD} -- -DSHIELD="${SHIELDS}" -DZMK_CONFIG=$(pwd)/${DIR} && \
    cp -r .build/${SHIELD}/zephyr/zmk.uf2 ${SHIELD}.uf2
done

#west build -s ../app -d .build/reset -b nice_nano_v2 -- -DSHIELD=settings_reset && cp -r .build/reset/zephyr/zmk.uf2 zmk_settings_reset.uf2
