name: Build master

on:
  push:
   branches:
     - master

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Create Keyboard Build Matrix
    outputs:
      build_matrix: ${{ env.build_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install yaml2json
        run: python3 -m pip install remarshal
      - name: Fetch Build Matrix
        id: build_matrix
        run: |
          result=$(for b in $(find boards -iname build.yaml)
          do
            variant=$(dirname $b | cut -d/ -f2)
            yaml2json $b | jq -c --arg variant $variant '.include[]|.variant=$variant'
          done | jq -nc '.include |= [inputs]')
          echo $result
          echo "build_matrix=$result" >> $GITHUB_ENV
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    needs: matrix
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.build_matrix) }}
    steps:
      - name: Prepare variables
        shell: sh -x {0}
        env:
          shield: ${{ matrix.shield }}
        run: |
          name=$(echo $shield|cut -d' ' -f1)
          if [ ! -z $(echo $name | grep -iE '_(left|right)$') ]
          then
            echo "artifact_name=${{matrix.variant}}_$(echo ${name} | rev | cut -d_ -f1 | rev)" >> $GITHUB_ENV
          else
            echo "artifact_name=${name:+$name-}${{ matrix.board }}-zmk" >> $GITHUB_ENV
          fi
          echo "zephyr_version=${ZEPHYR_VERSION}" >> $GITHUB_ENV
          echo "extra_cmake_args=${shield:+-DSHIELD=\"$shield\"}" >> $GITHUB_ENV
          echo "display_name=${{ matrix.variant }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache west modules
        uses: actions/cache@v3.0.11
        continue-on-error: true
        env:
          cache_name: cache-zephyr-${{ env.zephyr_version }}-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l "${GITHUB_WORKSPACE}"
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (${{ env.display_name }})
        shell: sh -x {0}
        run: |
          mkdir -p .build/artifacts
          west build -s ../zmk/app -d .build -b "${{ matrix.board }}" -- -DZMK_CONFIG="$(pwd)/boards/${{ matrix.variant }}" ${{ env.extra_cmake_args }} ${{ matrix.cmake-args }}
      - name: Rename artifacts
        shell: sh -x {0}
        run: |
          if [ -f .build/zephyr/zmk.uf2 ]
          then
            cp .build/zephyr/zmk.uf2 ".build/artifacts/${{ env.artifact_name }}.uf2"
          elif [ -f .build/zephyr/zmk.${{ inputs.fallback_binary }} ]
          then
            cp ".build/zephyr/zmk.${{ inputs.fallback_binary }}" ".build/artifacts/${{ env.artifact_name }}.${{ inputs.fallback_binary }}"
          fi
      - name: Archive (${{ env.display_name }})
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}
          path: .build/artifacts
